-- kade-duckbones: Duckbones with bright, readable comments
-- Direct conversion from zenbones-theme/zenbones.nvim duckbones.vim
-- Only modification: Comment color changed from #5A5F7B to #00A3CB (cyan)

local M = {}

function M.load(config)
  config = config or {}

  -- Terminal colors (exact from duckbones.vim)
  vim.g.terminal_color_0 = "#0E101A"
  vim.g.terminal_color_1 = "#E03600"
  vim.g.terminal_color_2 = "#5DCD97"
  vim.g.terminal_color_3 = "#E39500"
  vim.g.terminal_color_4 = "#00A3CB"
  vim.g.terminal_color_5 = "#795CCC"
  vim.g.terminal_color_6 = "#00A3CB"
  vim.g.terminal_color_7 = "#EBEFC0"
  vim.g.terminal_color_8 = "#2B2F46"
  vim.g.terminal_color_9 = "#FF4821"
  vim.g.terminal_color_10 = "#58DB9E"
  vim.g.terminal_color_11 = "#F6A100"
  vim.g.terminal_color_12 = "#00B4E0"
  vim.g.terminal_color_13 = "#B3A1E6"
  vim.g.terminal_color_14 = "#00B4E0"
  vim.g.terminal_color_15 = "#B3B692"

  local bg = config.transparent and "NONE" or "#0E101A"

  local hi = vim.api.nvim_set_hl

  -- Direct conversion from duckbones.vim
  hi(0, "Normal", { fg = "#EBEFC0", bg = bg })
  hi(0, "Bold", { bold = true })
  hi(0, "Boolean", { fg = "#EBEFC0", italic = true })
  hi(0, "BufferVisible", { fg = "#F0F5C4" })
  hi(0, "BufferVisibleIndex", { fg = "#F0F5C4" })
  hi(0, "BufferVisibleSign", { fg = "#F0F5C4" })
  hi(0, "CocMarkdownLink", { fg = "#00A3CB", underline = true })
  hi(0, "ColorColumn", { bg = "#443426" })

  -- KADE MODIFICATION: Bright cyan comments instead of muted #5A5F7B
  hi(0, "Comment", { fg = "#00A3CB", italic = true })

  hi(0, "Conceal", { fg = "#9EA080", bold = true, italic = true })
  hi(0, "Constant", { fg = "#AEB18D", italic = true })
  hi(0, "Cursor", { fg = "#0E101A", bg = "#EDF2C2" })
  hi(0, "CursorLine", { bg = "#161926" })
  hi(0, "CursorLineNr", { fg = "#EBEFC0", bold = true })
  hi(0, "Delimiter", { fg = "#6D759D" })
  hi(0, "DiagnosticError", { fg = "#E03600" })
  hi(0, "DiagnosticHint", { fg = "#795CCC" })
  hi(0, "DiagnosticInfo", { fg = "#00A3CB" })
  hi(0, "DiagnosticOk", { fg = "#5DCD97" })
  hi(0, "DiagnosticSignError", { fg = "#E03600" })
  hi(0, "DiagnosticSignHint", { fg = "#795CCC" })
  hi(0, "DiagnosticSignInfo", { fg = "#00A3CB" })
  hi(0, "DiagnosticSignOk", { fg = "#5DCD97" })
  hi(0, "DiagnosticSignWarn", { fg = "#E39500" })
  hi(0, "DiagnosticUnderlineError", { sp = "#E03600", undercurl = true })
  hi(0, "DiagnosticUnderlineHint", { sp = "#795CCC", undercurl = true })
  hi(0, "DiagnosticUnderlineInfo", { sp = "#00A3CB", undercurl = true })
  hi(0, "DiagnosticUnderlineOk", { sp = "#5DCD97", undercurl = true })
  hi(0, "DiagnosticUnderlineWarn", { sp = "#E39500", undercurl = true })
  hi(0, "DiagnosticVirtualTextError", { fg = "#E03600", bg = "#1E1818" })
  hi(0, "DiagnosticVirtualTextHint", { fg = "#795CCC", bg = "#1A191E" })
  hi(0, "DiagnosticVirtualTextInfo", { fg = "#00A3CB", bg = "#181A1B" })
  hi(0, "DiagnosticVirtualTextOk", { fg = "#5DCD97", bg = "#181A19" })
  hi(0, "DiagnosticVirtualTextWarn", { fg = "#E39500", bg = "#1B1918" })
  hi(0, "DiagnosticWarn", { fg = "#E39500" })
  hi(0, "DiffAdd", { bg = "#15251C" })
  hi(0, "DiffChange", { bg = "#17232A" })
  hi(0, "DiffDelete", { bg = "#311C1A" })
  hi(0, "DiffText", { fg = "#EBEFC0", bg = "#2A3E48" })
  hi(0, "Directory", { bold = true })
  hi(0, "Error", { fg = "#E03600" })
  hi(0, "FlashBackdrop", { fg = "#5A5F7B" })
  hi(0, "FlashLabel", { fg = "#EBEFC0", bg = "#004B5F" })
  hi(0, "FloatBorder", { fg = "#6B729B" })
  hi(0, "FloatTitle", { fg = "#EBEFC0", bg = "#222536", bold = true })
  hi(0, "FoldColumn", { fg = "#51587A", bold = true })
  hi(0, "Folded", { fg = "#9A9FBC", bg = "#272B3E" })
  hi(0, "Function", { fg = "#EBEFC0" })
  hi(0, "FzfLuaBufFlagAlt", { fg = "#00A3CB" })
  hi(0, "FzfLuaBufFlagCur", { fg = "#E39500" })
  hi(0, "FzfLuaBufNr", { fg = "#5DCD97" })
  hi(0, "FzfLuaFzfMatch", { fg = "#795CCC", bold = true })
  hi(0, "FzfLuaHeaderBind", { fg = "#5DCD97" })
  hi(0, "FzfLuaHeaderText", { fg = "#E39500" })
  hi(0, "FzfLuaLiveSym", { fg = "#E39500" })
  hi(0, "FzfLuaPathColNr", { fg = "#898FB1", bold = true })
  hi(0, "FzfLuaTabMarker", { fg = "#5DCD97" })
  hi(0, "FzfLuaTabTitle", { fg = "#00A3CB" })
  hi(0, "GitSignsAdd", { fg = "#5DCD97" })
  hi(0, "GitSignsChange", { fg = "#00A3CB" })
  hi(0, "GitSignsDelete", { fg = "#E03600" })
  hi(0, "IblIndent", { fg = "#1F212D" })
  hi(0, "IblScope", { fg = "#393D50" })
  hi(0, "Identifier", { fg = "#C6CAA1" })
  hi(0, "IncSearch", { fg = "#0E101A", bg = "#9A87DC", bold = true })
  hi(0, "Italic", { italic = true })
  hi(0, "LineNr", { fg = "#51587A" })
  hi(0, "LspInlayHint", { fg = "#596392", bg = "#161926" })
  hi(0, "MoreMsg", { fg = "#5DCD97", bold = true })
  hi(0, "NonText", { fg = "#484E6D" })
  hi(0, "NormalFloat", { bg = "#222536" })
  hi(0, "Number", { fg = "#AEB18D" })
  hi(0, "Pmenu", { bg = "#222536" })
  hi(0, "PmenuSbar", { bg = "#4B5170" })
  hi(0, "PmenuSel", { bg = "#383C55" })
  hi(0, "PmenuThumb", { bg = "#757DA3" })
  hi(0, "PreProc", { fg = "#00A3CB" })
  hi(0, "RenderMarkdownCode", { bg = "#161926" })
  hi(0, "Search", { fg = "#EBEFC0", bg = "#4D3191" })
  hi(0, "SnacksIndent", { fg = "#1F212D" })
  hi(0, "SnacksIndentScope", { fg = "#393D50" })
  hi(0, "SnacksPickerMatch", { fg = "#795CCC", bold = true })
  hi(0, "SneakLabelMask", { fg = "#795CCC", bg = "#795CCC" })
  hi(0, "Special", { fg = "#5DCD97" })
  hi(0, "SpecialComment", { fg = "#5A5F7B" })
  hi(0, "SpecialKey", { fg = "#484E6D", italic = true })
  hi(0, "SpellBad", { fg = "#CA4F40", undercurl = true })
  hi(0, "SpellCap", { fg = "#CA4F40", undercurl = true })
  hi(0, "SpellRare", { fg = "#CA4F40", undercurl = true })
  hi(0, "Statement", { fg = "#795CCC", bold = true })
  hi(0, "StatusLine", { fg = "#EBEFC0", bg = "#232738" })
  hi(0, "StatusLineNC", { fg = "#F0F5C4", bg = "#1A1D2B" })
  hi(0, "String", { fg = "#AEB18D", italic = true })
  hi(0, "TabLineSel", { bold = true })
  hi(0, "Title", { fg = "#EBEFC0", bold = true })
  hi(0, "Todo", { bold = true, underline = true })
  hi(0, "Type", { fg = "#898FB1" })
  hi(0, "Underlined", { underline = true })
  hi(0, "Visual", { bg = "#37382D" })
  hi(0, "WarningMsg", { fg = "#E39500" })
  hi(0, "WhichKeySeparator", { fg = "#51587A" })
  hi(0, "WildMenu", { fg = "#0E101A", bg = "#795CCC" })
  hi(0, "WinSeparator", { fg = "#51587A" })
  hi(0, "diffFile", { fg = "#E39500", bold = true })
  hi(0, "diffIndexLine", { fg = "#E39500" })
  hi(0, "diffLine", { fg = "#795CCC", bold = true })
  hi(0, "diffNewFile", { fg = "#5DCD97", italic = true })
  hi(0, "diffOldFile", { fg = "#E03600", italic = true })
  hi(0, "helpHyperTextEntry", { fg = "#898FB1", bold = true })
  hi(0, "helpHyperTextJump", { fg = "#C6CAA1", underline = true })
  hi(0, "lCursor", { fg = "#0E101A", bg = "#939677" })
  hi(0, "markdownLinkText", { fg = "#C6CAA1", underline = true })

  -- Links (exact from duckbones.vim)
  hi(0, "ModeMsg", { link = "Normal" })
  hi(0, "LspReferenceRead", { link = "ColorColumn" })
  hi(0, "LspReferenceText", { link = "ColorColumn" })
  hi(0, "LspReferenceWrite", { link = "ColorColumn" })
  hi(0, "Character", { link = "Constant" })
  hi(0, "TroubleSource", { link = "Constant" })
  hi(0, "WhichKeyValue", { link = "Constant" })
  hi(0, "helpOption", { link = "Constant" })
  hi(0, "TermCursor", { link = "Cursor" })
  hi(0, "CocMenuSel", { link = "CursorLine" })
  hi(0, "CursorColumn", { link = "CursorLine" })
  hi(0, "FzfLuaFzfCursorLine", { link = "CursorLine" })
  hi(0, "SnacksPickerListCursorLine", { link = "CursorLine" })
  hi(0, "SnacksPickerPreviewCursorLine", { link = "CursorLine" })
  hi(0, "markdownLinkTextDelimiter", { link = "Delimiter" })
  hi(0, "NotifyERRORIcon", { link = "DiagnosticError" })
  hi(0, "NotifyERRORTitle", { link = "DiagnosticError" })
  hi(0, "NotifyDEBUGIcon", { link = "DiagnosticHint" })
  hi(0, "NotifyDEBUGTitle", { link = "DiagnosticHint" })
  hi(0, "NotifyTRACEIcon", { link = "DiagnosticHint" })
  hi(0, "NotifyTRACETitle", { link = "DiagnosticHint" })
  hi(0, "NotifyINFOIcon", { link = "DiagnosticInfo" })
  hi(0, "NotifyINFOTitle", { link = "DiagnosticInfo" })
  hi(0, "CocErrorSign", { link = "DiagnosticSignError" })
  hi(0, "CocHintSign", { link = "DiagnosticSignHint" })
  hi(0, "CocInfoSign", { link = "DiagnosticSignInfo" })
  hi(0, "CocWarningSign", { link = "DiagnosticSignWarn" })
  hi(0, "CocErrorHighlight", { link = "DiagnosticUnderlineError" })
  hi(0, "CocHintHighlight", { link = "DiagnosticUnderlineHint" })
  hi(0, "CocInfoHighlight", { link = "DiagnosticUnderlineInfo" })
  hi(0, "CocWarningHighlight", { link = "DiagnosticUnderlineWarn" })
  hi(0, "CocErrorVirtualText", { link = "DiagnosticVirtualTextError" })
  hi(0, "CocWarningVirtualText", { link = "DiagnosticVirtualTextWarn" })
  hi(0, "DiagnosticDeprecated", { link = "DiagnosticWarn" })
  hi(0, "DiagnosticUnnecessary", { link = "DiagnosticWarn" })
  hi(0, "NotifyWARNIcon", { link = "DiagnosticWarn" })
  hi(0, "NotifyWARNTitle", { link = "DiagnosticWarn" })
  hi(0, "diffAdded", { link = "DiffAdd" })
  hi(0, "diffChanged", { link = "DiffChange" })
  hi(0, "diffRemoved", { link = "DiffDelete" })
  hi(0, "ErrorMsg", { link = "Error" })
  hi(0, "TroubleNormal", { link = "Function" })
  hi(0, "TroubleText", { link = "Function" })
  hi(0, "FzfLuaPathLineNr", { link = "FzfLuaPathColNr" })
  hi(0, "GitGutterAdd", { link = "GitSignsAdd" })
  hi(0, "GitGutterChange", { link = "GitSignsChange" })
  hi(0, "GitGutterDelete", { link = "GitSignsDelete" })
  hi(0, "IndentLine", { link = "IblIndent" })
  hi(0, "IndentLineCurrent", { link = "IblScope" })
  hi(0, "CurSearch", { link = "IncSearch" })
  hi(0, "CocCodeLens", { link = "LineNr" })
  hi(0, "LspCodeLens", { link = "LineNr" })
  hi(0, "SignColumn", { link = "LineNr" })
  hi(0, "Question", { link = "MoreMsg" })
  hi(0, "EndOfBuffer", { link = "NonText" })
  hi(0, "Whitespace", { link = "NonText" })
  hi(0, "SnacksPickerBorder", { link = "NormalFloat" })
  hi(0, "Float", { link = "Number" })
  hi(0, "CocSearch", { link = "Search" })
  hi(0, "MatchParen", { link = "Search" })
  hi(0, "QuickFixLine", { link = "Search" })
  hi(0, "Sneak", { link = "Search" })
  hi(0, "WhichKeyGroup", { link = "Special" })
  hi(0, "markdownUrl", { link = "SpecialComment" })
  hi(0, "CocSelectedText", { link = "SpellBad" })
  hi(0, "SpellLocal", { link = "SpellCap" })
  hi(0, "FzfLuaBufName", { link = "Statement" })
  hi(0, "WhichKey", { link = "Statement" })
  hi(0, "TabLine", { link = "StatusLine" })
  hi(0, "WinBar", { link = "StatusLine" })
  hi(0, "TabLineFill", { link = "StatusLineNC" })
  hi(0, "WinBarNC", { link = "StatusLineNC" })
  hi(0, "BufferCurrent", { link = "TabLineSel" })
  hi(0, "FzfLuaTitle", { link = "Title" })
  hi(0, "helpSpecial", { link = "Type" })
  hi(0, "markdownCode", { link = "Type" })
  hi(0, "gitcommitOverflow", { link = "WarningMsg" })
  hi(0, "SneakLabel", { link = "WildMenu" })
  hi(0, "VertSplit", { link = "WinSeparator" })
  hi(0, "TermCursorNC", { link = "lCursor" })

  -- TreeSitter highlights
  hi(0, "@comment", { link = "Comment" })
  hi(0, "@constant", { link = "Constant" })
  hi(0, "@string", { link = "String" })
  hi(0, "@character", { link = "Character" })
  hi(0, "@number", { link = "Number" })
  hi(0, "@boolean", { link = "Boolean" })
  hi(0, "@float", { link = "Float" })
  hi(0, "@function", { link = "Function" })
  hi(0, "@parameter", { link = "Identifier" })
  hi(0, "@method", { link = "Function" })
  hi(0, "@field", { link = "Identifier" })
  hi(0, "@property", { link = "Identifier" })
  hi(0, "@constructor", { link = "Type" })
  hi(0, "@conditional", { link = "Statement" })
  hi(0, "@repeat", { link = "Statement" })
  hi(0, "@label", { link = "Statement" })
  hi(0, "@operator", { fg = "#EBEFC0" })
  hi(0, "@keyword", { link = "Statement" })
  hi(0, "@exception", { link = "Statement" })
  hi(0, "@variable", { fg = "#EBEFC0" })
  hi(0, "@type", { link = "Type" })
  hi(0, "@namespace", { link = "Identifier" })
  hi(0, "@include", { link = "PreProc" })
  hi(0, "@preproc", { link = "PreProc" })
  hi(0, "@punctuation.delimiter", { link = "Delimiter" })
  hi(0, "@punctuation.bracket", { link = "Delimiter" })
  hi(0, "@punctuation.special", { link = "Special" })
  hi(0, "@tag", { link = "Statement" })
  hi(0, "@tag.attribute", { link = "Identifier" })
  hi(0, "@tag.delimiter", { link = "Delimiter" })
  hi(0, "@text", { fg = "#EBEFC0" })
  hi(0, "@text.strong", { bold = true })
  hi(0, "@text.emphasis", { italic = true })
  hi(0, "@text.underline", { underline = true })
  hi(0, "@text.title", { link = "Title" })
  hi(0, "@text.literal", { link = "Type" })
  hi(0, "@text.uri", { fg = "#00A3CB", underline = true })
  hi(0, "@text.todo", { link = "Todo" })

  -- LSP semantic tokens
  hi(0, "@lsp.type.comment", { link = "Comment" })
  hi(0, "@lsp.type.enum", { link = "Type" })
  hi(0, "@lsp.type.interface", { link = "Type" })
  hi(0, "@lsp.type.keyword", { link = "Statement" })
  hi(0, "@lsp.type.namespace", { link = "Identifier" })
  hi(0, "@lsp.type.parameter", { link = "Identifier" })
  hi(0, "@lsp.type.property", { link = "Identifier" })
  hi(0, "@lsp.type.variable", { fg = "#EBEFC0" })
end

return M
